### PR TITLE
Added ability to feed result into a temp file through separate command

### PR DESCRIPTION
**Pull request by boguscoder**

### CODE REVIEW

**Comment by boguscoder** [comment]
Please let me know if you accept contributions or abandoned plugin

**Comment by yhirose** [comment]
@boguscoder, thanks for the contribution!

**Comment by boguscoder** [comment]
no problem, please let me know if you can publish update to extension store
I can try PRing 'command history' that is one of the open issues

**Comment by yhirose** [comment]
I have just published the update. 
https://marketplace.visualstudio.com/items?itemName=yhirose.FilterText
You are always welcome to sending me PR!

**Pull request merged**
