### PR TITLE
Implemented passing in the command as an argument. Implements Github #1

### PR DESCRIPTION
**Pull request by mwick83**
The command can optionally be passed in as a hash map with a key "cmd"
of type string. This can be used in keybindings.json. The hash map is
used to possibly add more options being passed in the future.

### CODE REVIEW

**Comment by mwick83** [comment]
The diff looks rather big, but it's really only a new wrapper that checks in which variant the commands have been called and calls the refactored, old code.

**Comment by yhirose** [comment]
@mwick83, thanks for another contribution! Do you have any other PRs coming? If not, I'll bump up the version number to 0.0.13.

**Comment by mwick83** [comment]
You are welcome! No, currently not, but I just started to use the extension quiet regularly, so I'll see, what I come up with next ;) So, I think bumping the version now is a good idea.

**Comment by yhirose** [comment]
Done!
https://marketplace.visualstudio.com/items?itemName=yhirose.FilterText

**Pull request merged**
