### PR TITLE
Fix #9, for new file (e.g. untitled), the current directory should st…

### LINKED ISSUE #9: Set current working directory for the command to match the opened directory
I was happy to discover this extension and will use it heavily. However, there is one change which would make it even more convenient for me.

I'd like to execute e.g. ```wc -l *```, but currently (at least on Windows) that would give contents from the installation directory (*C:\Program Files (x86)\Microsoft VS Code*).

To work  around the issue I currently need to explicitly start a shell and switch to the correct directory, e.g:

    cmd /c "cd MYDIRECTORY && wc -l *"

I can think of several alternatives for the default directory:
* Take the directory of the current editor
* If the current editor is Untitled-x, take the directory opened in VS Code
* If there is no directory opened, just individual files, pick one of their directories
* Default to user's home directory

Maybe there could be a directory selection box below the command input box which shows the alternatives but would allow the user to type something different (combo box).

### PR DESCRIPTION
**Pull request by johnnytemp**
…ill be a first workspace folder, if any workspace folder is opened.  Otherwise, default to user's home directory.

To reproduce, type Cmd-N or Ctrl-N to create a new file.  Invoke Filter Text and type `pwd` and enter.

### CODE REVIEW

**Comment by johnnytemp** [comment]
Still some issue pending to fix.  Please wait.

**Comment by johnnytemp** [comment]
Implemented the suggestion same as the table in:
https://github.com/yhirose/vscode-filtertext/issues/9#issuecomment-362235943

**Comment by yhirose** [comment]
Look good to me. Thanks for the fix! I'll release the new version soon.

**Comment by johnnytemp** [comment]
Thanks!

**Pull request merged**
